"""Drive ``dotnet sonarscanner begin/end`` around a .NET build — non-blocking.

C# and VB.NET cannot be analyzed by the plain ``sonar-scanner`` CLI. SonarSource
states it outright — *"These languages can't be analyzed with the SonarScanner
CLI"* — because C# issues are produced by Roslyn analyzers that ``begin`` injects
into the compilation. ``end`` then *"collects the analysis data generated by the
build"*. No compile between the two steps means no analysis at all.

That single fact is why this module exists rather than another branch in
:mod:`brimyr.sonar`: for .NET the scanner **wraps** the run instead of following
it. The shape is

    begin  →  dotnet build --no-incremental  →  dotnet test (coverage)  →  end

and the coverage report path is declared at **begin**, as a wildcard, because the
reports do not exist yet and ``end`` accepts only three flags
(``sonar.token``, ``sonar.clientcert.password``, ``sonar.scanner.truststorePassword``).

Same contract as :mod:`brimyr.sonar`: **failure-isolated**. Nothing here raises,
the gate never depends on it, and the token travels in the environment rather than
on argv so it cannot leak into a process listing.
"""

from __future__ import annotations

import os
import shutil
from collections.abc import Iterator, Mapping, Sequence
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path

from brimyr.sonar import Runner, SonarConfig, SonarResult, _default_runner

# Left behind by `begin` and consumed by `end`. If `end` never runs, this directory
# still holds the injected build hooks, and a later build in the same workspace picks
# them up and fails in a way that has nothing to do with the build.
_WORK_DIR = ".sonarqube"


@dataclass
class SessionOutcome:
    """What the begin/end pair did. Never an exception — always a report."""

    begin: SonarResult | None = None
    end: SonarResult | None = None
    cleaned: bool = False
    skipped: str | None = None
    commands: list[tuple[str, ...]] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return self.end is not None and self.end.ok

    @property
    def started(self) -> bool:
        return self.begin is not None and self.begin.ok

    @property
    def message(self) -> str | None:
        """One line for the job summary / PR comment footer."""
        if self.skipped:
            return f"skipped ({self.skipped})"
        if self.begin is not None and not self.begin.ok:
            return self.begin.message
        if self.end is None:
            return "analysis started but never finished (non-blocking); .sonarqube cleaned"
        if self.end.ok:
            return "analysis uploaded (SonarScanner for .NET)"
        return self.end.message


def build_begin_args(
    config: SonarConfig,
    *,
    report_globs: Mapping[str, Sequence[str]] | None = None,
    scanner_bin: str = "dotnet",
) -> list[str]:
    """Assemble ``dotnet sonarscanner begin`` argv. The token is NOT included."""
    args = [scanner_bin, "sonarscanner", "begin", f"/d:sonar.host.url={config.host_url}"]
    if config.project_key:
        args.append(f"/k:{config.project_key}")
    if config.organization:
        args.append(f"/o:{config.organization}")
    for prop, globs in (report_globs or {}).items():
        if prop and globs:
            args.append(f"/d:{prop}={','.join(str(g) for g in globs)}")
    # `-Dfoo=bar` (CLI flavour) is `/d:foo=bar` here; accept either from the caller so
    # a consumer does not have to know which scanner their repo happens to use.
    for extra in config.extra_args:
        args.append(f"/d:{extra[2:]}" if extra.startswith("-D") else extra)
    return args


def build_end_args(scanner_bin: str = "dotnet") -> list[str]:
    """Assemble ``dotnet sonarscanner end`` argv.

    Deliberately bare. ``end`` accepts only three flags and every other property —
    project key, host URL, the coverage path — must have been given at ``begin``.
    The token is read from ``SONAR_TOKEN`` in the environment.
    """
    return [scanner_bin, "sonarscanner", "end"]


def _run(argv: list[str], repo: str | Path, env: dict[str, str], runner: Runner) -> SonarResult:
    try:
        completed = runner(argv, str(repo), env)
    except FileNotFoundError:
        return SonarResult(
            False,
            "skipped (dotnet-sonarscanner not found — "
            "`dotnet tool install --global dotnet-sonarscanner`)",
            command=tuple(argv),
        )
    except OSError as exc:
        return SonarResult(False, f"could not run dotnet sonarscanner: {exc}", command=tuple(argv))

    if completed.returncode == 0:
        return SonarResult(True, "ok", returncode=0, command=tuple(argv))
    detail = (getattr(completed, "stderr", "") or getattr(completed, "stdout", "") or "").strip()
    return SonarResult(
        False,
        f"dotnet sonarscanner failed (exit {completed.returncode}, non-blocking): {detail[:300]}",
        returncode=completed.returncode,
        command=tuple(argv),
    )


@contextmanager
def session(
    config: SonarConfig,
    repo: str | Path = ".",
    *,
    report_globs: Mapping[str, Sequence[str]] | None = None,
    runner: Runner | None = None,
    base_env: Mapping[str, str] | None = None,
) -> Iterator[SessionOutcome]:
    """``begin`` on entry, ``end`` on exit — **always**, including on an exception.

    The body is the build and test run. Nothing raised by ``begin`` or ``end`` escapes;
    it lands in the yielded :class:`SessionOutcome` instead. Exceptions raised by the
    *body* propagate untouched — a broken test run is the caller's verdict to make, and
    swallowing it here would turn a red build green.

    If ``begin`` succeeded but ``end`` did not run or failed, ``.sonarqube`` is removed.
    Nothing has reached the server either way (upload happens at ``end``), but the
    directory holds the injected MSBuild hooks, and leaving it behind makes the *next*
    build in that workspace fail for reasons that look unrelated.
    """
    outcome = SessionOutcome()
    run_fn = runner or _default_runner
    env = dict(base_env if base_env is not None else os.environ)

    if not config.host_url:
        outcome.skipped = "no SonarQube host URL set"
        yield outcome
        return
    if not config.token:
        outcome.skipped = "no SonarQube token set"
        yield outcome
        return

    env["SONAR_TOKEN"] = config.token
    begin_argv = build_begin_args(config, report_globs=report_globs)
    outcome.commands.append(tuple(begin_argv))
    outcome.begin = _run(begin_argv, repo, env, run_fn)

    try:
        yield outcome
    finally:
        if outcome.begin is not None and outcome.begin.ok:
            end_argv = build_end_args()
            outcome.commands.append(tuple(end_argv))
            outcome.end = _run(end_argv, repo, env, run_fn)
            if not outcome.end.ok:
                outcome.cleaned = _cleanup(repo)


def _cleanup(repo: str | Path) -> bool:
    """Remove ``.sonarqube``. Best effort — a failure here must not surface."""
    try:
        shutil.rmtree(Path(repo) / _WORK_DIR)
    except OSError:
        return False
    return True
